version: "3.7"

services:
  livecode_1:
    image: mysql:latest
    container_name: livecode_1
    ports:
      - 3306:3306
    environment:       
      - MYSQL_ROOT_PASSWORD=admin 
      - MYSQL_DB=livecode
    volumes: 
      - mysqldata:/data/mysql
      
volumes:
  mysqldata:
    driver: local